name: Release-Build

on: workflow_dispatch

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/release.yml@v6
